[package]
name = "treelog"
version = "0.1.0"
authors = ["konrad <szymoniak.konrad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
grep = "0.2.7"
